### ISSUE TITLE
Can't resolve 'fs' in '.../node_modlues/eml-format/lib'

### ISSUE THREAD

**Issue by barrymichaeldoyle** [papnkukn/eml-format#8]
After added this mailparser package to my project I get the following error:

> Error: Can't resolve 'fs' in '{projectPath}/node_modules/html-to-text/lib'

I've been trying various fixes but one fix just leads to another. How do I get around this issue?

**Comment by pl12133** [comment]
Due to the dependency on `fs`, this module is not isomorphic; it cannot be run in a browser.

The `parse` function can be run in the browser because it doesn't depend on `fs`, but you need to modify the module yourself:

1. Create a local copy of [`eml-format.js`](https://github.com/papnkukn/eml-format/blob/master/lib/eml-format.js).
2. Remove the function that depends on `fs`: [`emlformat.unpack`](https://github.com/papnkukn/eml-format/blob/master/lib/eml-format.js#L115).
3. Import your local copy of `eml-format.js` instead of this module.

It would be nice if the underlying parser was exposed as it's own module without the `fs` dependency.

**Comment by papnkukn** [comment]
@pl12133 thanks for providing the answer.

The `fs` dependency has been moved inside the `unpack` function. Thus, the `parse` and other functions should now be available when running the script in a browser.
